// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: api/pod/v1/pod.proto

package v1

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Pod service

func NewPodEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Pod service

type PodService interface {
	AddPod(ctx context.Context, in *AddPodRequest, opts ...client.CallOption) (*AddPodResponse, error)
	DeletePod(ctx context.Context, in *DeletePodRequest, opts ...client.CallOption) (*DeletePodResponse, error)
	FindPodByID(ctx context.Context, in *FindPodByIDRequest, opts ...client.CallOption) (*FindPodByIDResponse, error)
	UpdatePod(ctx context.Context, in *UpdatePodRequest, opts ...client.CallOption) (*UpdatePodResponse, error)
	FindAllPods(ctx context.Context, in *FindAllPodsRequest, opts ...client.CallOption) (*FindAllPodsResponse, error)
}

type podService struct {
	c    client.Client
	name string
}

func NewPodService(name string, c client.Client) PodService {
	return &podService{
		c:    c,
		name: name,
	}
}

func (c *podService) AddPod(ctx context.Context, in *AddPodRequest, opts ...client.CallOption) (*AddPodResponse, error) {
	req := c.c.NewRequest(c.name, "Pod.AddPod", in)
	out := new(AddPodResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podService) DeletePod(ctx context.Context, in *DeletePodRequest, opts ...client.CallOption) (*DeletePodResponse, error) {
	req := c.c.NewRequest(c.name, "Pod.DeletePod", in)
	out := new(DeletePodResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podService) FindPodByID(ctx context.Context, in *FindPodByIDRequest, opts ...client.CallOption) (*FindPodByIDResponse, error) {
	req := c.c.NewRequest(c.name, "Pod.FindPodByID", in)
	out := new(FindPodByIDResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podService) UpdatePod(ctx context.Context, in *UpdatePodRequest, opts ...client.CallOption) (*UpdatePodResponse, error) {
	req := c.c.NewRequest(c.name, "Pod.UpdatePod", in)
	out := new(UpdatePodResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podService) FindAllPods(ctx context.Context, in *FindAllPodsRequest, opts ...client.CallOption) (*FindAllPodsResponse, error) {
	req := c.c.NewRequest(c.name, "Pod.FindAllPods", in)
	out := new(FindAllPodsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Pod service

type PodHandler interface {
	AddPod(context.Context, *AddPodRequest, *AddPodResponse) error
	DeletePod(context.Context, *DeletePodRequest, *DeletePodResponse) error
	FindPodByID(context.Context, *FindPodByIDRequest, *FindPodByIDResponse) error
	UpdatePod(context.Context, *UpdatePodRequest, *UpdatePodResponse) error
	FindAllPods(context.Context, *FindAllPodsRequest, *FindAllPodsResponse) error
}

func RegisterPodHandler(s server.Server, hdlr PodHandler, opts ...server.HandlerOption) error {
	type pod interface {
		AddPod(ctx context.Context, in *AddPodRequest, out *AddPodResponse) error
		DeletePod(ctx context.Context, in *DeletePodRequest, out *DeletePodResponse) error
		FindPodByID(ctx context.Context, in *FindPodByIDRequest, out *FindPodByIDResponse) error
		UpdatePod(ctx context.Context, in *UpdatePodRequest, out *UpdatePodResponse) error
		FindAllPods(ctx context.Context, in *FindAllPodsRequest, out *FindAllPodsResponse) error
	}
	type Pod struct {
		pod
	}
	h := &podHandler{hdlr}
	return s.Handle(s.NewHandler(&Pod{h}, opts...))
}

type podHandler struct {
	PodHandler
}

func (h *podHandler) AddPod(ctx context.Context, in *AddPodRequest, out *AddPodResponse) error {
	return h.PodHandler.AddPod(ctx, in, out)
}

func (h *podHandler) DeletePod(ctx context.Context, in *DeletePodRequest, out *DeletePodResponse) error {
	return h.PodHandler.DeletePod(ctx, in, out)
}

func (h *podHandler) FindPodByID(ctx context.Context, in *FindPodByIDRequest, out *FindPodByIDResponse) error {
	return h.PodHandler.FindPodByID(ctx, in, out)
}

func (h *podHandler) UpdatePod(ctx context.Context, in *UpdatePodRequest, out *UpdatePodResponse) error {
	return h.PodHandler.UpdatePod(ctx, in, out)
}

func (h *podHandler) FindAllPods(ctx context.Context, in *FindAllPodsRequest, out *FindAllPodsResponse) error {
	return h.PodHandler.FindAllPods(ctx, in, out)
}
